"""add trade enum to skills and jobs

Revision ID: 1eff08b170d6
Revises: 989350a9dd8d
Create Date: 2026-09-11 13:35:23.651503

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1eff08b170d6'
down_revision: Union[str, Sequence[str], None] = '989350a9dd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    trade_enum = sa.Enum(
        'PLUMBING', 'ELECTRICAL', 'SOLAR', 'WELDING', 'BUILDING', 'APPLIANCE_REPAIR',
        name='tradeenum',
    )
    trade_enum.create(op.get_bind())

    op.add_column('jobs', sa.Column('trade', trade_enum, nullable=False))
    op.alter_column(
        'skills', 'trade',
        existing_type=sa.VARCHAR(length=50),
        type_=trade_enum,
        existing_nullable=False,
        postgresql_using='trade::text::tradeenum',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'skills', 'trade',
        existing_type=sa.Enum(
            'PLUMBING', 'ELECTRICAL', 'SOLAR', 'WELDING', 'BUILDING', 'APPLIANCE_REPAIR',
            name='tradeenum',
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        postgresql_using='trade::text',
    )
    op.drop_column('jobs', 'trade')

    sa.Enum(name='tradeenum').drop(op.get_bind())
    # ### end Alembic commands ###
