"""add indexes on foreign key columns

Revision ID: 4fa80902185b
Revises: 447e4d827227
Create Date: 2026-09-11 17:48:49.650756

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4fa80902185b'
down_revision: Union[str, Sequence[str], None] = '447e4d827227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crew_members_worker_id'), 'crew_members', ['worker_id'], unique=False)
    op.create_index(
        op.f('ix_crew_order_ledger_entries_crew_order_id'),
        'crew_order_ledger_entries',
        ['crew_order_id'],
        unique=False,
    )
    op.create_index(op.f('ix_crew_orders_buyer_id'), 'crew_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_crew_orders_crew_id'), 'crew_orders', ['crew_id'], unique=False)
    op.create_index(op.f('ix_disputes_job_id'), 'disputes', ['job_id'], unique=False)
    op.create_index(op.f('ix_disputes_raised_by_id'), 'disputes', ['raised_by_id'], unique=False)
    op.create_index(op.f('ix_jobs_buyer_id'), 'jobs', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_jobs_worker_id'), 'jobs', ['worker_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_job_id'), 'ledger_entries', ['job_id'], unique=False)
    op.create_index(op.f('ix_persons_guarantor_id'), 'persons', ['guarantor_id'], unique=False)
    op.create_index(
        op.f('ix_record_entries_worker_id'), 'record_entries', ['worker_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_entries_worker_id'), table_name='record_entries')
    op.drop_index(op.f('ix_persons_guarantor_id'), table_name='persons')
    op.drop_index(op.f('ix_ledger_entries_job_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_jobs_worker_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_buyer_id'), table_name='jobs')
    op.drop_index(op.f('ix_disputes_raised_by_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_job_id'), table_name='disputes')
    op.drop_index(op.f('ix_crew_orders_crew_id'), table_name='crew_orders')
    op.drop_index(op.f('ix_crew_orders_buyer_id'), table_name='crew_orders')
    op.drop_index(
        op.f('ix_crew_order_ledger_entries_crew_order_id'),
        table_name='crew_order_ledger_entries',
    )
    op.drop_index(op.f('ix_crew_members_worker_id'), table_name='crew_members')
    # ### end Alembic commands ###
