"""Initial schema

Revision ID: 7165c54ce358
Revises: 
Create Date: 2026-09-06 16:59:18.084291

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7165c54ce358'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column(
        'role', sa.Enum('BUYER', 'WORKER', 'OPS', 'AGGREGATOR', name='roleenum'), nullable=False
    ),
    sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True),
    sa.Column('guarantor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guarantor_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column(
        'status',
        sa.Enum(
            'REQUESTED', 'MATCHED', 'BOOKED', 'IN_PROGRESS', 'DISPUTED', 'COMPLETED', 'CANCELLED',
            name='jobstatusenum',
        ),
        nullable=False,
    ),
    sa.Column('suburb', sa.String(length=100), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('problem_photo_url', sa.String(length=255), nullable=True),
    sa.Column('quote_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('suburb', sa.String(length=100), nullable=False),
    sa.Column('travel_means', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('proof_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standings',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('on_time_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dispute_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fill_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column(
        'entry_type',
        sa.Enum(
            'DEPOSIT_HELD', 'BALANCE_COMMITTED', 'RELEASED', 'REFUNDED',
            name='ledgerentrytypeenum',
        ),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('what_was_done', sa.Text(), nullable=False),
    sa.Column('client_words', sa.Text(), nullable=True),
    sa.Column('before_photo_url', sa.String(length=255), nullable=True),
    sa.Column('after_photo_url', sa.String(length=255), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_entries')
    op.drop_table('ledger_entries')
    op.drop_table('standings')
    op.drop_table('skills')
    op.drop_table('service_areas')
    op.drop_table('jobs')
    op.drop_table('persons')
    # ### end Alembic commands ###
    sa.Enum(name='ledgerentrytypeenum').drop(op.get_bind())
    sa.Enum(name='jobstatusenum').drop(op.get_bind())
    sa.Enum(name='roleenum').drop(op.get_bind())
