"""add crew tables and composite unique constraints

Revision ID: a725b45e4046
Revises: 7165c54ce358
Create Date: 2026-09-11 13:18:02.440103

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a725b45e4046'
down_revision: Union[str, Sequence[str], None] = '7165c54ce358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('crew_members',
    sa.Column('crew_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('crew_id', 'worker_id')
    )
    op.create_unique_constraint(
        'uq_service_areas_worker_suburb', 'service_areas', ['worker_id', 'suburb']
    )
    op.create_unique_constraint('uq_skills_worker_trade', 'skills', ['worker_id', 'trade'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_skills_worker_trade', 'skills', type_='unique')
    op.drop_constraint('uq_service_areas_worker_suburb', 'service_areas', type_='unique')
    op.drop_table('crew_members')
    op.drop_table('crews')
    # ### end Alembic commands ###
