"""add landmark narrative and gps pin to jobs and crew orders

Revision ID: b4bcfbff527d
Revises: a8bea2064338
Create Date: 2026-09-18 11:32:20.916535

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4bcfbff527d'
down_revision: Union[str, Sequence[str], None] = 'a8bea2064338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_orders', sa.Column('landmark_narrative', sa.Text(), nullable=True))
    op.add_column(
        'crew_orders', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True)
    )
    op.add_column(
        'crew_orders', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True)
    )
    op.add_column('jobs', sa.Column('landmark_narrative', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('jobs', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'longitude')
    op.drop_column('jobs', 'latitude')
    op.drop_column('jobs', 'landmark_narrative')
    op.drop_column('crew_orders', 'longitude')
    op.drop_column('crew_orders', 'latitude')
    op.drop_column('crew_orders', 'landmark_narrative')
    # ### end Alembic commands ###
