"""add suburbs reference table and fk constraints

Revision ID: e17014832001
Revises: 1eff08b170d6
Create Date: 2026-09-11 13:46:10.748029

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e17014832001'
down_revision: Union[str, Sequence[str], None] = '1eff08b170d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


suburbs_table = sa.table(
    'suburbs',
    sa.column('name', sa.String),
    sa.column('latitude', sa.Numeric),
    sa.column('longitude', sa.Numeric),
)

# Approximate suburb centroids for MVP distance banding (Stage One pilot,
# Bulawayo). Refine with surveyed coordinates before widening coverage.
SEED_SUBURBS = [
    {"name": "Nkulumane", "latitude": -20.2050, "longitude": 28.5300},
    {"name": "Njube", "latitude": -20.1970, "longitude": 28.5420},
    {"name": "Entumbane", "latitude": -20.2200, "longitude": 28.5500},
    {"name": "Luveve", "latitude": -20.1550, "longitude": 28.5300},
    {"name": "Hillside", "latitude": -20.1850, "longitude": 28.6300},
    {"name": "Kumalo", "latitude": -20.1750, "longitude": 28.6450},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suburbs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.bulk_insert(suburbs_table, SEED_SUBURBS)
    op.create_foreign_key('fk_jobs_suburb', 'jobs', 'suburbs', ['suburb'], ['name'])
    op.create_foreign_key(
        'fk_service_areas_suburb', 'service_areas', 'suburbs', ['suburb'], ['name']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_service_areas_suburb', 'service_areas', type_='foreignkey')
    op.drop_constraint('fk_jobs_suburb', 'jobs', type_='foreignkey')
    op.drop_table('suburbs')
    # ### end Alembic commands ###
