"""add disputes table

Revision ID: fded931081b3
Revises: b5c95ae9abd2
Create Date: 2026-09-11 14:07:41.620902

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fded931081b3'
down_revision: Union[str, Sequence[str], None] = 'b5c95ae9abd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column(
        'status',
        sa.Enum('OPEN', 'RESOLVED_RETURN_VISIT', name='disputestatusenum'),
        nullable=False,
    ),
    sa.Column('worker_response', sa.Text(), nullable=True),
    sa.Column('before_photo_url', sa.String(length=255), nullable=True),
    sa.Column('after_photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disputes')
    # ### end Alembic commands ###
    sa.Enum(name='disputestatusenum').drop(op.get_bind())
